// Opt-in: creates its own NEW business in an explicitly identified isolated project.
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {SupabaseStore} from '../src/store.js';
import {handleMessage} from '../src/service.js';
import {interpret} from '../src/interpret.js';
const env=process.env;
if(env.ALLOW_LIVE_SMOKE!=='isolated-project'||!env.TEST_USER_ID||!env.SUPABASE_PROJECT_REF_CONFIRM||new URL(env.SUPABASE_URL).hostname!==`${env.SUPABASE_PROJECT_REF_CONFIRM}.supabase.co`||!env.GEMINI_API_KEY) throw new Error('Configure the explicit isolated-project opt-in, project reference, test Auth user and API key.');
const store=new SupabaseStore();const actor=env.TEST_USER_ID;const business=randomUUID();
await store.request('profiles?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=ignore-duplicates,return=minimal'},body:JSON.stringify({id:actor,display_name:'Piloto Sprint 1'})});
await store.request('businesses',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({id:business,name:`Smoke Sprint 1 ${new Date().toISOString()}`,timezone:'America/Mexico_City'})});
await store.request('memberships',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({business_id:business,user_id:actor})});
const send=(text,id=randomUUID())=>handleMessage({store,interpreter:interpret,actor,business,channel:'web',externalId:id,text});
const id=randomUUID();const first=await send('Vendí 3 playeras en $900',id);assert.equal(first.amount_cents,90000);
assert.equal((await send('Vendí 3 playeras en $900',id)).duplicate,true);
const total=await send('¿Cuánto vendí hoy?');assert.equal(total.sales_cents,90000);
const filter=`business_id=eq.${business}`;
const messages=await store.request(`messages?${filter}&select=id,external_id,response`);
const movements=await store.request(`movements?${filter}&select=id,kind,amount_cents,source_message_id`);
const audit=await store.request(`movement_audit?${filter}&select=id,movement_id,action`);
assert.equal(messages.length,2);
assert.equal(messages.filter(message=>message.external_id===id).length,1);
assert.equal(movements.length,1);
assert.equal(movements[0].kind,'sale');
assert.equal(movements[0].amount_cents,90000);
assert.equal(audit.length,1);
assert.equal(audit[0].movement_id,movements[0].id);
assert.equal(audit[0].action,'create');
console.log(JSON.stringify({passed:true,business_id:business,result:total.text,messages:messages.length,movements:movements.length,audit:audit.length,note:'Dedicated test business retained for inspection. No existing ledger was changed.'},null,2));
